// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: broler_grpc.proto

package broler_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Broler_FoundLink_FullMethodName = "/broler.Broler/FoundLink"
)

// BrolerClient is the client API for Broler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrolerClient interface {
	FoundLink(ctx context.Context, in *FoundLinkArg, opts ...grpc.CallOption) (*Pages, error)
}

type brolerClient struct {
	cc grpc.ClientConnInterface
}

func NewBrolerClient(cc grpc.ClientConnInterface) BrolerClient {
	return &brolerClient{cc}
}

func (c *brolerClient) FoundLink(ctx context.Context, in *FoundLinkArg, opts ...grpc.CallOption) (*Pages, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pages)
	err := c.cc.Invoke(ctx, Broler_FoundLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrolerServer is the server API for Broler service.
// All implementations must embed UnimplementedBrolerServer
// for forward compatibility.
type BrolerServer interface {
	FoundLink(context.Context, *FoundLinkArg) (*Pages, error)
	mustEmbedUnimplementedBrolerServer()
}

// UnimplementedBrolerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrolerServer struct{}

func (UnimplementedBrolerServer) FoundLink(context.Context, *FoundLinkArg) (*Pages, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FoundLink not implemented")
}
func (UnimplementedBrolerServer) mustEmbedUnimplementedBrolerServer() {}
func (UnimplementedBrolerServer) testEmbeddedByValue()                {}

// UnsafeBrolerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrolerServer will
// result in compilation errors.
type UnsafeBrolerServer interface {
	mustEmbedUnimplementedBrolerServer()
}

func RegisterBrolerServer(s grpc.ServiceRegistrar, srv BrolerServer) {
	// If the following call pancis, it indicates UnimplementedBrolerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Broler_ServiceDesc, srv)
}

func _Broler_FoundLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FoundLinkArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrolerServer).FoundLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broler_FoundLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrolerServer).FoundLink(ctx, req.(*FoundLinkArg))
	}
	return interceptor(ctx, in, info, handler)
}

// Broler_ServiceDesc is the grpc.ServiceDesc for Broler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Broler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "broler.Broler",
	HandlerType: (*BrolerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FoundLink",
			Handler:    _Broler_FoundLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "broler_grpc.proto",
}
