// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: broler_grpc.proto

package broler_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FoundLinkArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoundLinkArg) Reset() {
	*x = FoundLinkArg{}
	mi := &file_broler_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoundLinkArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoundLinkArg) ProtoMessage() {}

func (x *FoundLinkArg) ProtoReflect() protoreflect.Message {
	mi := &file_broler_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoundLinkArg.ProtoReflect.Descriptor instead.
func (*FoundLinkArg) Descriptor() ([]byte, []int) {
	return file_broler_grpc_proto_rawDescGZIP(), []int{0}
}

type Paths struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsEnd         bool                   `protobuf:"varint,1,opt,name=is_end,json=isEnd,proto3" json:"is_end,omitempty"`
	Paths         map[string]*Paths      `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Paths) Reset() {
	*x = Paths{}
	mi := &file_broler_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Paths) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paths) ProtoMessage() {}

func (x *Paths) ProtoReflect() protoreflect.Message {
	mi := &file_broler_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paths.ProtoReflect.Descriptor instead.
func (*Paths) Descriptor() ([]byte, []int) {
	return file_broler_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *Paths) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

func (x *Paths) GetPaths() map[string]*Paths {
	if x != nil {
		return x.Paths
	}
	return nil
}

type Pages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          map[string]*Paths      `protobuf:"bytes,1,rep,name=root,proto3" json:"root,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pages) Reset() {
	*x = Pages{}
	mi := &file_broler_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pages) ProtoMessage() {}

func (x *Pages) ProtoReflect() protoreflect.Message {
	mi := &file_broler_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pages.ProtoReflect.Descriptor instead.
func (*Pages) Descriptor() ([]byte, []int) {
	return file_broler_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *Pages) GetRoot() map[string]*Paths {
	if x != nil {
		return x.Root
	}
	return nil
}

var File_broler_grpc_proto protoreflect.FileDescriptor

const file_broler_grpc_proto_rawDesc = "" +
	"\n" +
	"\x11broler_grpc.proto\x12\x06broler\"\x0e\n" +
	"\fFoundLinkArg\"\x97\x01\n" +
	"\x05Paths\x12\x15\n" +
	"\x06is_end\x18\x01 \x01(\bR\x05isEnd\x12.\n" +
	"\x05paths\x18\x02 \x03(\v2\x18.broler.Paths.PathsEntryR\x05paths\x1aG\n" +
	"\n" +
	"PathsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.broler.PathsR\x05value:\x028\x01\"|\n" +
	"\x05Pages\x12+\n" +
	"\x04root\x18\x01 \x03(\v2\x17.broler.Pages.RootEntryR\x04root\x1aF\n" +
	"\tRootEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.broler.PathsR\x05value:\x028\x012<\n" +
	"\x06Broler\x122\n" +
	"\tFoundLink\x12\x14.broler.FoundLinkArg\x1a\r.broler.Pages\"\x00B*Z(github.com/aavtic/broler/rpc/broler_grpcb\x06proto3"

var (
	file_broler_grpc_proto_rawDescOnce sync.Once
	file_broler_grpc_proto_rawDescData []byte
)

func file_broler_grpc_proto_rawDescGZIP() []byte {
	file_broler_grpc_proto_rawDescOnce.Do(func() {
		file_broler_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_broler_grpc_proto_rawDesc), len(file_broler_grpc_proto_rawDesc)))
	})
	return file_broler_grpc_proto_rawDescData
}

var file_broler_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_broler_grpc_proto_goTypes = []any{
	(*FoundLinkArg)(nil), // 0: broler.FoundLinkArg
	(*Paths)(nil),        // 1: broler.Paths
	(*Pages)(nil),        // 2: broler.Pages
	nil,                  // 3: broler.Paths.PathsEntry
	nil,                  // 4: broler.Pages.RootEntry
}
var file_broler_grpc_proto_depIdxs = []int32{
	3, // 0: broler.Paths.paths:type_name -> broler.Paths.PathsEntry
	4, // 1: broler.Pages.root:type_name -> broler.Pages.RootEntry
	1, // 2: broler.Paths.PathsEntry.value:type_name -> broler.Paths
	1, // 3: broler.Pages.RootEntry.value:type_name -> broler.Paths
	0, // 4: broler.Broler.FoundLink:input_type -> broler.FoundLinkArg
	2, // 5: broler.Broler.FoundLink:output_type -> broler.Pages
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_broler_grpc_proto_init() }
func file_broler_grpc_proto_init() {
	if File_broler_grpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_broler_grpc_proto_rawDesc), len(file_broler_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_broler_grpc_proto_goTypes,
		DependencyIndexes: file_broler_grpc_proto_depIdxs,
		MessageInfos:      file_broler_grpc_proto_msgTypes,
	}.Build()
	File_broler_grpc_proto = out.File
	file_broler_grpc_proto_goTypes = nil
	file_broler_grpc_proto_depIdxs = nil
}
